# Generated by Django 3.0.7 on 2020-07-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=20)),
                ('m_phone', models.CharField(max_length=20)),
                ('m_email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=20)),
                ('fphone', models.CharField(max_length=20)),
                ('f_email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(max_length=20)),
                ('g_phone', models.CharField(max_length=20)),
                ('g_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
