# Generated by Django 3.0.7 on 2020-07-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200705_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
