# Generated by Django 3.0.7 on 2020-07-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_delete_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
