# Generated by Django 3.0.7 on 2020-07-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
