# Generated by Django 3.0.7 on 2020-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200705_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateTimeField(),
        ),
    ]
