# Generated by Django 3.0.7 on 2020-07-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20200706_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sname',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
