# Generated by Django 3.0.7 on 2020-07-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20200706_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
