# Generated by Django 3.0.7 on 2020-07-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0010_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('section', models.CharField(max_length=6)),
            ],
        ),
    ]
