# Generated by Django 3.0.7 on 2020-07-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='g_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='parent',
            name='g_phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='parent',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
