# Generated by Django 3.0.7 on 2020-07-09 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date_s',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
