# Generated by Django 3.0.7 on 2020-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_enquiry_date_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_s',
            field=models.DateField(null=True),
        ),
    ]
