# Generated by Django 3.0.7 on 2020-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_assignment_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_upload',
            name='subject',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
