# Generated by Django 3.0.7 on 2020-07-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_rv_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rv_upload',
            name='pdf',
        ),
        migrations.AddField(
            model_name='rv_upload',
            name='mp4',
            field=models.FileField(blank=True, upload_to='books/pdfs'),
        ),
    ]
