# Generated by Django 3.0.7 on 2020-07-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_auto_20200721_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=20)),
                ('std', models.IntegerField()),
                ('sec', models.CharField(max_length=1)),
                ('pdf', models.FileField(blank=True, upload_to='books/pdfs')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40)),
                ('submission_attach', models.FileField(blank=True, upload_to='books/pdfs')),
                ('submission_attach1', models.FileField(blank=True, upload_to='books/pdfs')),
                ('submission_attach2', models.FileField(blank=True, upload_to='books/pdfs')),
                ('status', models.CharField(max_length=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='testapp.Assignment')),
            ],
        ),
    ]
