# Generated by Django 3.0.7 on 2020-07-26 06:00

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_assignment_assignment_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rlink_upload',
            name='url',
        ),
    ]
