# Generated by Django 3.0.7 on 2020-07-26 06:06

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_auto_20200726_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlink_upload',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
